### ISSUE TITLE
[1.7.10] Console spam.

### ISSUE THREAD

**Issue by m0nkm0nk** [Darkhax-Minecraft/WAWLA#81]
As requested, a new thread about the console spam.

Cleared the log, rebooted MC, joined the server and instantly it came up with the spamming errors when entering an inventory. See from line 45149 till end of file.

Full log:
http://www.swe-gaming.com/paste.txt

**Comment by darkhax** [comment]
Thanks, looking at the issue, the problem is with the sanguimancy mod and not related to WAWLA. 

```
[23:20:30] [NEI Item Filtering/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent@5d7357bc:
java.lang.NullPointerException
	at cpw.mods.fml.common.registry.GameRegistry$UniqueIdentifier.<init>(GameRegistry.java:389) ~[GameRegistry$UniqueIdentifier.class:?]
	at cpw.mods.fml.common.registry.GameData.getUniqueName(GameData.java:239) ~[GameData.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.findUniqueIdentifierFor(GameRegistry.java:462) ~[GameRegistry.class:?]
	at tombenpotter.sanguimancy.util.EventHandler$ClientEventHandler.onSanguimancyItemTooltip(EventHandler.java:402) ~[EventHandler$ClientEventHandler.class:1.7.10-1.1.9-35]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_2138_ClientEventHandler_onSanguimancyItemTooltip_ItemTooltipEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:169) [ForgeEventFactory.class:?]
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:626) [add.class:?]
	at codechicken.nei.guihook.GuiContainerManager.itemDisplayNameMultiline(GuiContainerManager.java:119) [GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.concatenatedDisplayName(GuiContainerManager.java:162) [GuiContainerManager.class:?]
	at codechicken.nei.api.ItemInfo.getSearchName(ItemInfo.java:529) [ItemInfo.class:?]
	at codechicken.nei.ItemList$PatternItemFilter.matches(ItemList.java:65) [ItemList$PatternItemFilter.class:?]
	at codechicken.nei.ItemList$AnyMultiItemFilter.matches(ItemList.java:110) [ItemList$AnyMultiItemFilter.class:?]
	at codechicken.nei.ItemList$AllMultiItemFilter.matches(ItemList.java:85) [ItemList$AllMultiItemFilter.class:?]
	at codechicken.nei.ItemList$2.execute(ItemList.java:239) [ItemList$2.class:?]
	at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24) [RestartableTask$1.class:?]
```
