### ISSUE TITLE
Latest Wawla version crashes server on server boot

### ISSUE THREAD

**Issue by kerts93** [Darkhax-Minecraft/WAWLA#96]
After updating Wawla in our modpack to version `Wawla-1.12.2-2.5.260.jar` it crashes our server on launch. Reverting only this back to version `Wawla-1.12.2-2.5.257.jar` everything works.

Here is the crash log:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.7.4.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  MtqFixPlugin (mtqfix-1.12.2-1.1.0.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 9/6/18 10:16 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from What Are We Looking At (wawla)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at net.darkhax.wawla.plugins.generic.PluginEnchantmentDescription.<init>(PluginEnchantmentDescription.java:35)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.darkhax.wawla.utils.AnnotationUtils.getAnnotations(AnnotationUtils.java:115)
	at net.darkhax.wawla.plugins.FeatureManager.init(FeatureManager.java:24)
	at net.darkhax.wawla.Wawla.preInit(Wawla.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@4c9e38 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 46 more
Caused by: java.lang.RuntimeException: Attempted to load class bib for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 48 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.9.0-7-amd64
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 442969144 bytes (422 MB) / 1269583872 bytes (1210 MB) up to 17145004032 bytes (16350 MB)
	JVM Flags: 7 total; -XX:MaxPermSize=256M -Xmx16G -Xms1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=4 -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2759 72 mods loaded, 71 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version           | Source                                                               | Signature                                |
	|:----- |:-------------------------------------------- |:----------------- |:-------------------------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                                    | 1.12.2            | minecraft.jar                                                        | None                                     |
	| UCH   | mcp                                          | 9.42              | minecraft.jar                                                        | None                                     |
	| UCH   | FML                                          | 8.0.99.99         | ForgeMod.jar                                                         | None                                     |
	| UCH   | forge                                        | 14.23.4.2759      | ForgeMod.jar                                                         | None                                     |
	| UCH   | com.elytradev.movingworld.common.asm.coremod |                   | minecraft.jar                                                        | None                                     |
	| UCH   | opencomputers|core                           | 1.7.2.67          | minecraft.jar                                                        | None                                     |
	| UCH   | bdlib                                        | 1.14.3.12         | bdlib-1.14.3.12-mc1.12.2.jar                                         | None                                     |
	| UCH   | bibliocraft                                  | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                                    | None                                     |
	| UCH   | mts                                          | 10.1.2            | Minecraft Transport Simulator-1.12.2-10.1.2.jar                      | None                                     |
	| UCH   | btcivilmts                                   | 4.0.0             | BlackThorne Civilian Pack BETA [MTS Edition] 1.12.2-10.1.1-1.4.0.jar | None                                     |
	| UCH   | buildinggadgets                              | 1.6.2             | BuildingGadgets-1.6.2.jar                                            | None                                     |
	| UCH   | chameleon                                    | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                                             | None                                     |
	| UCH   | chisel                                       | MC1.12.2-0.2.1.34 | Chisel-MC1.12.2-0.2.1.34.jar                                         | None                                     |
	| UCH   | codechickenlib                               | 3.2.1.351         | CodeChickenLib-1.12.2-3.2.1.351-universal.jar                        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux                                 | 2.0.2             | RedstoneFlux-1.12-2.0.2.3-universal.jar                              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | cofhcore                                     | 4.5.3             | CoFHCore-1.12.2-4.5.3.20-universal.jar                               | None                                     |
	| UCH   | cofhworld                                    | 1.2.0             | CoFHWorld-1.12.2-1.2.0.5-universal.jar                               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | crafttweaker                                 | 4.1.9             | CraftTweaker2-1.12-4.1.9.jar                                         | None                                     |
	| UCH   | mtlib                                        | 3.0.5             | MTLib-3.0.5.jar                                                      | None                                     |
	| UCH   | modtweaker                                   | 4.0.13            | modtweaker-4.0.13.jar                                                | None                                     |
	| UCH   | jei                                          | 4.11.0.212        | jei_1.12.2-4.11.0.212.jar                                            | None                                     |
	| UCH   | crafttweakerjei                              | 2.0.2             | CraftTweaker2-1.12-4.1.9.jar                                         | None                                     |
	| UCH   | movingworld                                  | 1.12-6.342        | movingworld-1.12-6.342-full.jar                                      | None                                     |
	| UCH   | davincisvessels                              | @DVESSELSVER@     | davincisvessels-1.12-6.340-full.jar                                  | None                                     |
	| UCH   | discordintegration                           | 3.0.4             | DiscordIntegration-mc1.12.2-3.0.5.jar                                | None                                     |
	| UCH   | dynmap                                       | 2.6-beta-1-21     | Dynmap-2.6-beta-1-forge-1.12.2.jar                                   | None                                     |
	| UCH   | mantle                                       | 1.12-1.3.2.24     | Mantle-1.12-1.3.2.24.jar                                             | None                                     |
	| UCH   | tconstruct                                   | 1.12.2-2.10.1.87  | TConstruct-1.12.2-2.10.1.87.jar                                      | None                                     |
	| UCH   | extrautils2                                  | 1.0               | extrautils2-1.12-1.9.1.jar                                           | None                                     |
	| UCH   | opencomputers                                | 1.7.2.67          | OpenComputers-MC1.12.2-1.7.2.67.jar                                  | None                                     |
	| UCH   | zerocore                                     | 1.12-0.1.2.2      | zerocore-1.12-0.1.2.2.jar                                            | None                                     |
	| UCH   | bigreactors                                  | 1.12.2-0.4.5.49   | ExtremeReactors-1.12.2-0.4.5.49.jar                                  | None                                     |
	| UCH   | fcl                                          | XII.42            | Fexcraft Common Library-XII.42.jar                                   | None                                     |
	| UCH   | forestry                                     | 5.8.1.322         | forestry_1.12.2-5.8.1.322.jar                                        | None                                     |
	| UCH   | forgelin                                     | 1.7.4             | Forgelin-1.7.4.jar                                                   | None                                     |
	| UCH   | frsm                                         | 4.0.27b           | FRSM-4.0.27b.jar                                                     | None                                     |
	| UCH   | fsmm                                         | 2.2.1             | FSMM-2.2.1-1.12.x.jar                                                | None                                     |
	| UCH   | ftblib                                       | 5.3.0.48          | FTBLib-5.3.0.48.jar                                                  | None                                     |
	| UCH   | ftbutilities                                 | 5.3.0.48          | FTBUtilities-5.3.0.48.jar                                            | None                                     |
	| UCH   | gendustry                                    | 1.6.5.8           | gendustry-1.6.5.8-mc1.12.2.jar                                       | None                                     |
	| UCH   | gendustryjei                                 | 1.0.2             | gendustryjei-1.0.2.jar                                               | None                                     |
	| UCH   | gravestone                                   | 1.10.1            | gravestone-1.10.1.jar                                                | None                                     |
	| UCH   | waila                                        | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                                          | None                                     |
	| UCH   | thermalfoundation                            | 2.5.0             | ThermalFoundation-1.12.2-2.5.0.19-universal.jar                      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | immersiveengineering                         | 0.12-85           | ImmersiveEngineering-0.12-85.jar                                     | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCH   | immersivepetroleum                           | 1.1.9             | immersivepetroleum-1.12.2-1.1.9.jar                                  | None                                     |
	| UCH   | trackapi                                     | 1.1               | TrackAPI-1.1_1.12.jar                                                | None                                     |
	| UCH   | immersiverailroading                         | 1.3.2             | ImmersiveRailroading-1.3.2_1.12.jar                                  | None                                     |
	| UCH   | teslacorelib                                 | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | industrialforegoing                          | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.11.2-212.jar                            | None                                     |
	| UCH   | inventorysorter                              | 1.13.3+57         | inventorysorter-1.12.2-1.13.3+57.jar                                 | None                                     |
	| UCH   | ironchest                                    | 1.12.2-7.0.40.824 | ironchest-1.12.2-7.0.40.824.jar                                      | None                                     |
	| UCH   | journeymap                                   | 1.12.2-5.5.2      | journeymap-1.12.2-5.5.2.jar                                          | None                                     |
	| UCH   | laggoggles                                   | FORGE-1.12.2-4.1  | LagGoggles-FORGE-1.12.2-4.1.jar                                      | None                                     |
	| UCH   | morebees                                     | 1.12.2-2.0.1      | morebees-1.12.2-2.0.1.jar                                            | None                                     |
	| UCH   | morpheus                                     | 1.12-3.3.2        | Morpheus-1.12-3.3.2.jar                                              | None                                     |
	| UCH   | mtspackoffical                               | 4.0.0             | MTS_Offical_Pack_V04.jar                                             | None                                     |
	| UCH   | thermalexpansion                             | 5.5.0             | ThermalExpansion-1.12.2-5.5.0.29-universal.jar                       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | redstonearsenal                              | 2.5.1             | RedstoneArsenal-1.12.2-2.5.1.13-universal.jar                        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | refinedstorage                               | 1.6.4             | refinedstorage-1.6.4.jar                                             | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCH   | refinedstorageaddons                         | 0.4.2             | refinedstorageaddons-0.4.2.jar                                       | None                                     |
	| UCH   | storagedrawers                               | 1.12-5.3.5        | StorageDrawers-1.12.2-5.3.7.jar                                      | None                                     |
	| UCH   | thermalcultivation                           | 0.3.0             | ThermalCultivation-1.12.2-0.3.0.7-universal.jar                      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | thermaldynamics                              | 2.5.1             | ThermalDynamics-1.12.2-2.5.1.14-universal.jar                        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | thermalinnovation                            | 0.3.0             | ThermalInnovation-1.12.2-0.3.0.7-universal.jar                       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | thutcore                                     | 5.19.7            | thutcore-1.12.2-5.19.7.jar                                           | None                                     |
	| UCH   | thutcore_compat                              | 1.0               | thutcore-1.12.2-5.19.7.jar                                           | None                                     |
	| UCH   | thuttech                                     | 6.1.4             | thuttech-1.12.2-6.1.4.jar                                            | None                                     |
	| UCEE  | wawla                                        | 2.5.260           | Wawla-1.12.2-2.5.260.jar                                             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | worldedit                                    | 6.1.8             | worldedit-forge-mc1.12-6.1.8-dist.jar                                | None                                     |
	| UC    | teslacorelib_registries                      | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar                                     | None                                     |
	| UD    | mtqfix                                       | 1.1.0             | minecraft.jar                                                        | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.7.4.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
MtqFixPlugin (mtqfix-1.12.2-1.1.0.jar)
  jmn.mods.mtqfix.AsmTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* bigreactors|API (4.0.1) from ExtremeReactors-1.12.2-0.4.5.49.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.1.34.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.1.34.jar
		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.5.3.20-universal.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* discordrp-api (0.0.3) from DiscordRP-1.12.2-1.2.0.13.jar
		* discordrp-api|rpc (0.0.1) from DiscordRP-1.12.2-1.2.0.13.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.1.322.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.8-mc1.12.2.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-85.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-85.jar
		* industrialforegoingapi (5) from industrialforegoing-1.12.2-1.11.2-212.jar
		* jeresources|API (0.8.5.27) from JustEnoughResources-1.12.2-0.8.5.27.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.11.0.212.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.12.1.jar
		* opencomputersapi|component (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|core (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|driver (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|driver|item (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|event (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|filesystem (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|internal (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|machine (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|manual (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|network (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* opencomputersapi|prefab (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.2.67.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* thut|API (1.0.0) from thutcore-1.12.2-5.19.7.jar
		* WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2.jar
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by darkhax** [comment]
This should be fixed, just waiting on curse to review the file. https://minecraft.curseforge.com/projects/wawla-what-are-we-looking-at/files/2613883
